language: julia

# for building petri nets in docs
sudo: required
os:
  - linux
  - osx
  - windows

dist: trusty

julia:
  - 1.0
  - nightly

matrix:
  allow_failures:
    - julia: 1.0
    - julia: nightly

notifications:
  email: false
cache:
  directories:
  - test/kernels
  after_success:
    # Push coverage results to Coveralls.
    - julia -e 'import Pkg; cd(Pkg.dir("Biomodelling")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
    # Push coverage results to Codecov.
    - julia -e 'import Pkg; cd(Pkg.dir("Biomodelling")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

#script: # the default script is equivalent to the following
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Example"); Pkg.test("Example"; coverage=true)';
