language: julia

# for building petri nets in docs
sudo: required
os:
  - linux
  - osx
  - windows

dist: trusty

julia:
  - nightly

matrix:
  allow_failures:
    - julia: 1.0
    - julia: nightly

notifications:
  email: false
cache:
  directories:
  - test/kernels

after_success:
  - if [[ $TRAVIS_OS_NAME = linux ]]; then
      julia --project=coverage/ -e 'using Pkg; Pkg.instantiate();
          using Coverage; Codecov.submit(Codecov.process_folder())';
    fi
