language: julia

# for building petri nets in docs
sudo: required
os:
  - linux
  - osx

dist: trusty

julia:
  - 1.0
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

after_success:
  - if [[ $TRAVIS_OS_NAME = linux ]]; then
      julia --project=coverage/ -e 'using Pkg; Pkg.instantiate();
          using Coverage; Codecov.submit(Codecov.process_folder())';
    fi
